config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: 'blog/posts#index'

  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
      put 'publish' => 'posts#publish', on: :member
      put 'unpublish' => 'posts#unpublish', on: :member
    end
  end

  scope module: 'blog' do
    get 'about' => 'pages#about', as: :about, path: 'sobre'
    get 'contact' => 'pages#contact', as: :contact, path: 'contato'
    get 'gifs' => 'pages#gifs', as: :giphy, path: 'gifs'
    get 'posts' => 'posts#index', as: :posts, path: 'postagens'
    # get 'posts/:id' => 'posts#show', as: :post
    scope :path => '/postagens', :controller => :posts do
      get '/:id' => :show, :as => 'post'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # um autor pode ter varias postagens
  has_many :posts

  # exige que seja passado o parametro nome para realizar o update do autor
  validates_presence_of :name, on: :update

  # printa o nome do autor ou 'autor' como default
  def display_name
    name.present? ? name : 'Autor'
  end
end

app/models/giphy.rb
class Giphy < ApplicationRecord
  include HTTParty

  # url base da api de gifs utilizada
  base_uri 'https://api.giphy.com/v1/gifs'
  # parametros necessarios para utilizacao da api
  default_params api_key: '250b38ae3f3040e3b626254166186990', limit: 50, offset: 0, rating: 'G', lang: 'en'
  format :json

  def self.search_items(gif)
    get('/search', query: { q: gif })["data"]
  end
end

app/models/post.rb
class Post < ApplicationRecord

  acts_as_taggable # Alias for acts_as_taggable_on :tags

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :author

  PER_PAGE = 5

  # ordenara as postagens na ordem decrescente quando forem criadas
  scope :most_recent, -> { order(published_at: :desc) }

  scope :published, -> {where(published: true)}
  scope :recent_paginated, -> (page) { most_recent.page(page).per(PER_PAGE) }
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  scope :list_for, -> (page, tag) do
    recent_paginated(page).with_tag(tag)
  end

  # verifica se o titulo do post foi alterado e altera na url amigavel
  def should_generate_new_friendly_id?
    title_changed?
  end

  # mostra a data e hora de publicacao da postagem
  def display_day_published
    if published_at.present?
      "Publicado em #{published_at.strftime('%-d/%-m/%-Y as %-H:%-M')}"
    else
      "Postagem não publicada ainda."
    end
  end

  def publish
    update(published: true, published_at: Time.now)
  end

  def unpublish
    update(published: false, published_at: nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'author'
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  before_action :authenticate_author!
end

app/controllers/authors/accounts_controller.rb
module Authors
  class AccountsController < AuthorController

    def edit
    end

    def update_info
      if current_author.update(author_info_params)
        flash[:success] = 'Dados alterados com sucesso.'
      else
        flash[:danger] = 'Ocorreu um erro, revise seus dados.'
      end
      redirect_to authors_account_path
    end

    def change_password
      author = current_author
      if author.valid_password?(author_password_params[:current_password])
        if author.update(
            password: author_password_params[:new_password],
            password_confirmation: author_password_params[:new_password_confirmation]
          )

          sign_in(author, bypass: true)
          flash[:success] = 'Senha alterada com sucesso!'
        else
          flash[:danger] = 'Dados inválidos.'
        end
      else
        flash[:danger] = 'Senha atual errada.'
      end
      redirect_to authors_account_path
    end

    private

    def author_info_params
      params.require(:author).permit(:name, :email, :bio)
    end

    def author_password_params
      params.require(:author).permit(:current_password, :new_password, :new_password_confirmation)
    end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorController
    before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

    # GET /posts
    # GET /posts.json
    def index
      @posts = current_author.posts.most_recent
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
      @post = current_author.posts.new
    end

    # GET /posts/1/edit
    def edit
    end

    def publish
      @post.publish
      redirect_to authors_posts_url
    end

    def unpublish
      @post.unpublish
      redirect_to authors_posts_url
    end

    # POST /posts
    # POST /posts.json
    def create
      @post = current_author.posts.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to authors_post_path(@post), notice: 'Postagem foi criada com sucesso.' }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to authors_post_path(@post), notice: 'Postagem foi atualizada com sucesso.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to authors_posts_url, notice: 'Postagem foi deletada com sucesso.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.friendly.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def post_params
        params.require(:post).permit(:title, :body, :description, :banner_image_url, :box_notification, :tag_list)
      end
  end
end

app/controllers/blog/pages_controller.rb
module Blog
  class PagesController < BlogController

    def about
    end

    def contact
    end

    def gifs
      # recebe a string que foi digitada no input como parametro
      @search_gif = params[:giphy][:gif] if params[:giphy].present?
      # salva na variavel giphys o resultado do metodo de busca usando o parametro digitado
      @giphys = Giphy.search_items(@search_gif)
    end
  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController
    
    # GET /posts
    # GET /posts.json
    def index
      @posts = storage.list_for(params[:page], params[:tag])
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = storage.friendly.find(params[:id])
    end

    private

    def storage
      Post.published
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/giphy_helper.rb
module GiphyHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/accounts/edit.html.erb
<div style="margin-top: 50px;" class="columns">
  <!-- Atualização dos dado do Autor -->
  <div class="container is-fluid column is-4">
    <%= form_tag authors_info_path, method: :put do %> 
      <%= fields_for :author do |f| %>
          <p class="title is-3">Informações do Autor</p>
          <div class="field">
            <%= f.label :name, 'Nome do Autor', class: 'label', placeholder: 'teste' %>
            <%= f.text_field :name, placeholder: current_author.name, class: 'input column is-6' %>
          </div>

          <div class="field">
            <%= f.label :email, 'Email do Autor', class: 'label' %>
            <%= f.text_field :email, placeholder: current_author.email, class: 'input column is-8' %>
          </div>

          <div class="field">
            <%= f.label :bio, 'Bio do Autor', class: 'label' %>
            <%= f.text_area :bio, placeholder: current_author.bio, class: 'textarea' %>
          </div>
          <div class="actions">
            <%= f.submit 'Atualizar Dados', style: 'float:left', class: 'button is-success' %>
          </div>
      <% end %>
    <% end %>
  </div>

  <!-- Atualização de Senha -->
  <div class="container is-fluid column is-4 is-offset-2">
    <%= form_tag authors_change_password_path, method: :put do %> 
      <%= fields_for :author do |f| %>
          <p class="title is-3">Trocar senha</p>
          <div class="field">
            <%= f.label :current_password, 'Senha atual', class: 'label' %>
            <%= f.password_field :current_password, class: 'input column is-6' %>
          </div>

          <div class="field">
            <%= f.label :new_password, 'Nova senha', class: 'label' %>
            <%= f.password_field :new_password, class: 'input column is-6' %>
          </div>

          <div class="field">
            <%= f.label :new_password_confirmation, 'Confirme a senha', class: 'label' %>
            <%= f.password_field :new_password_confirmation, class: 'input column is-6' %>
          </div>
          <div class="actions">
            <%= f.submit 'Atualizar Senha', style: 'float:left', class: 'button is-warning' %>
          </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |f| %>
  <div style="margin-top: 50px; margin-bottom: 50px;" class="column is-10">
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title, 'Título', class: 'label' %>
      <%= f.text_field :title, class: 'input column is-4' %>
    </div>

    <div class="field">
      <%= f.label :banner_image_url, 'Imagem da postagem na tela inicial', class: 'label' %>
      <%= f.text_field :banner_image_url, class: 'input column is-4' %>
    </div>

    <div class="field">
      <%= f.label :box_notification, 'Define a cor da box que conterá a descrição', class: 'label' %>
      <span class="select">
      <%= f.select :box_notification, options_for_select([ "notification is-primary", "notification is-success", "notification is-warning", "notification is-danger", "notification is-info" ], "notification is-info") %>
      </span>
    </div>
    
    <div class="field">
      <%= f.label :body, 'Conteúdo da postagem', class: 'label' %>
      <%= f.text_area :body, class: 'textarea' %>
    </div>

    <div class="field">
      <%= f.label :tag_list, 'Tags para categoriazar a postagem', class: 'label' %>
      <%= f.text_area :tag_list, class: 'textarea' %>
    </div>

    <div class="field">
      <%= f.label :description, 'Descrição da postagem', class: 'label' %>
      <%= f.text_area :description, class: 'textarea' %>
    </div>
    <div class="actions">
      <%= f.submit style: 'float:right', class: 'button is-success' %>
    </div>
    <div style="float: left;">
      <% if @post.persisted? %>
        <%= link_to 'Exibir', authors_post_path(@post), class: 'button is-primary' %>
      <% end %>
      <%= link_to 'Voltar', authors_posts_path, class: 'button' %>
    </div>
  </div>
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
	<% if post.published? %>
		<td><%= link_to 'Despublicar', unpublish_authors_post_path(post), method: :put, class: 'button is-primary' %> </td>
	<% else %>
		<td><%= link_to 'Publicar', publish_authors_post_path(post), method: :put, class: 'button is-primary' %> </td>
	<% end %>
	<td><%= link_to 'Editar', edit_authors_post_path(post), class: 'button is-warning' %> </td>
	<td><%= link_to 'Deletar', authors_post_path(post), class: 'button is-danger', method: :delete, data: {confirm: 'Vinni você tem certeza de que deseja deletar essa postagem?'}%> </td>
</tr>

app/views/authors/posts/edit.html.erb
<% provide(:page_title, "Editando #{@post.title}")%>
<% provide(:author_active, 'is-active')%>

<div style="margin-top: 50px;" class="container is-fluid">
	<h1 class="title is-2"><%=yield(:page_title)%></h1>
	<%= render 'form', post: @post, url: authors_post_url(@post)  %>
</div>

app/views/authors/posts/index.html.erb
<% provide(:page_title, 'Todos os posts')%>
<% provide(:author_active, 'is-active')%>

<div style="margin-top: 50px;" class="container">
  <p id="notice"><%= notice %></p>
  <%= link_to t('new_post'), new_authors_post_path, class: 'button is-info' %>
  <table style="margin-top: 50px;" class="table">
  	<tr>
  		<th>Título</th>
      <th>Publicar/Despublicar</th>
  		<th>Editar</th>
      <th>Deletar</th>
  	</tr>
	  <% @posts.each do |post| %>
	    <%= render post %>
	  <%end%>
  </table>
</div>

app/views/authors/posts/new.html.erb
<% provide(:page_title, 'Novo Post')%>
<% provide(:author_active, 'is-active')%>

<div style="margin-top: 50px;" class="container is-fluid">
	<h1 class="title is-2"><%= t('new_post') %></h1>
	<%= render 'form', post: @post, url: authors_posts_url %>
</div>

app/views/authors/posts/show.html.erb
<% provide(:page_title, @post.title)%>
<% provide(:blog_active, 'is-active')%>

<div style="margin-top: 50px; margin-bottom: 50px;" class="container">
	<h1 class="title is-2"><%= @post.title %></h1>
	<p style="font-size: 13px;" class="tile notification column is-4"><%= @post.display_day_published%></p>
	<%= link_to 'Editar', edit_authors_post_path(@post), class: 'button is-warning' %>
	<%= link_to 'Deletar', authors_post_path(@post), class: 'button is-danger', method: :delete, data: {confirm: 'Vinni você tem certeza de que deseja deletar essa postagem?'}%>
	<div style="margin-top: 30px;" class="column is-12">
		<div class="tile notification"><%= @post.body.html_safe %></div>
	</div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:about_active, 'is-active')%>

<p style="text-align: center; margin-top: 50px;" class="title is-2">
	Conteúdo ainda será adicionado.
</p>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, 'is-active')%>

<p style="text-align: center; margin-top: 50px;" class="title is-2">
	Conteúdo ainda será adicionado.
</p>

app/views/blog/pages/gifs.html.erb
<% provide(:gifs_active, 'is-active')%>
<div class="column is-8 is-offset-4">
  <%= form_tag gifs_path, method: :get do %>
    <%= fields_for :giphy do |g| %> 
      <p class="title is-3">Gifs</p>
      <div class="columns">
        <%= g.text_field :gif, placeholder: 'Exemplo: meme', class: 'input column is-4' %>
        <%= g.submit 'Buscar', style: 'margin-left: 10px;', class: 'button is-info' %>
      </div>
      <div class="actions">
      </div>
    <% end %>
  <% end %>
</div>
<div class="">
  <% @giphys.each do |gif| %>
  <div class="container">
    <div class="column is-3">
      <img src="<%=gif["images"]["original"]["url"]%>">
    </div>
  </div>
  <% end %>
</div>

app/views/blog/posts/_post.html.erb
<div style="margin-top: 50px; margin-bottom: 50px;" class="container">
	<div class="column is-8 is-offset-2">
		<p class="title is-3"><%= post.title %></p>
		<figure style="max-height: 300px; max-width: 300px;">
		  <img src="<%= post.banner_image_url %>">
		</figure>
		<p style="margin-bottom: 5px;"><%= raw post.tags.map { |t| link_to t.name, posts_path(tag: t.name), class: 'tag is-black'}.join(' ')%></p>
		<p style="font-size: 13px;" class="tile notification column is-4"><%= post.display_day_published%></p>
		<div style="margin-top: 10px;" class="<%= post.box_notification %>">
			<p><%=truncate(post.description, length: 100)%></p>
			<p style="margin-top: 5px;"><%=link_to 'Continue na brisa...', post, class: 'button is-light is-small' %></p>
		</div>
	</div>
</div>

app/views/blog/posts/index.html.erb
<% provide(:page_title, 'Todos os posts')%>
<% provide(:blog_active, 'is-active')%>
<div style="text-align: center;" class="column is-4 is-offset-4">
  <%=image_tag('think-cloud')%>
</div>
<div style="margin-top: 50px;" class="container">
  <% @posts.each do |post| %>
    <%= render post %>
  <%end%>
</div>
  <div class="column is-4 is-offset-4">
    <%= paginate @posts %>
  </div>
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
    	<p><i class="fa fa-copyright" aria-hidden="true"></i> 2017 Brisadao. Todos os direitos reservados.</p>
    </div>
  </div>
</footer>

app/views/blog/posts/show.html.erb
<% provide(:page_title, @post.title)%>
<% provide(:blog_active, 'is-active')%>

<div style="margin-top: 50px; margin-bottom: 50px;" class="container">
	<h1 class="title is-2"><%= @post.title %></h1>
	<p style="font-size: 13px;" class="tile notification column is-3"><%= @post.display_day_published%></p>
	<div style="margin-top: 30px;" class="column is-10 is-offset-1">
		<div class="tile notification"><%= @post.body.html_safe %></div>
    <p style="margin-top: 25px;" class="title is-5">Compartilhe essa brisa !</p>
    <%= social_share_button_tag(@post.body.html_safe) %>
  </div>
	<!--<div style="margin-top: 25px;" class="column is-10 is-offset-1">-->
    <!-- Box de comentarios do Disquis, deixarei comentado por enquanto 
    <div id="disqus_thread"></div>
    <noscript>
      Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
    </noscript>
  </div> -->                              
</div>

<!-- script do Disquis comentado para nao gerar erros -->
<!--<script>
  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

  var disqus_config = function () {
    this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.slug %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };

  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://brisadao-blog.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>-->

app/views/layouts/_navbar.html.erb
<nav class="nav has-shadow">
  <div class="nav-left">
    <%= link_to 'Brisadao', root_path, class: "nav-item #{yield(:blog_active)}"%>
  </div>

  <!-- This "nav-toggle" hamburger menu is only visible on mobile -->
  <!-- You need JavaScript to toggle the "is-active" class on "nav-menu" -->
  <span id="nav-toggle" class="nav-toggle">
    <span></span>
    <span></span>
    <span></span>
  </span>

  <!-- This "nav-menu" is hidden on mobile -->
  <!-- Add the modifier "is-active" to display it on mobile -->
  <div id="nav-menu" class="nav-right nav-menu">
    <%= link_to 'Início', root_path, class: "nav-item #{yield(:blog_active)}"%>
    <%= link_to 'Gifs', gifs_path, class: "nav-item #{yield(:gifs_active)}"%>
    <%= link_to 'Sobre', about_path, class: "nav-item #{yield(:about_active)}"%>
    <%= link_to 'Contato', contact_path, class: "nav-item #{yield(:contact_active)}"%>
    <% if author_signed_in? %>
      <%= link_to 'Minhas Postagens', authors_posts_path, class: "nav-item #{yield(:author_active)}"%>
      <%= link_to 'Gerenciar Conta', authors_account_path, class: "nav-item #{yield(:account_active)}"%>
      <%= link_to 'Sair', destroy_author_session_path, method: :delete, class: "nav-item"%>
    <% end %>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brisadao Blog | <%=yield(:page_title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bulma' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=j1nx5vua5utvbv6x1h0jifebd2yjtjn1ozo63829cjniu03c"></script>
    <link href="https://use.fontawesome.com/d5100610f6.css" media="all" rel="stylesheet">
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="<%= controller_name %> <%= action_name %>">
      <!-- box de mensagem de sucesso e falha -->
      <% if flash.any? %>
        <% flash.keys.each do |key| %>
          <% if flash.keys.first.to_s == 'danger' %>
            <article style="margin-top: 10px;" class="container is-fluid message is-danger">
              <div class="message-header">
                <p><strong>Erro !</strong></p>
                <button class="delete"></button>
              </div>
              <div class="message-body">
              <%= flash[key] %>
              </div>
            </article>
          <% else %>
            <article style="margin-top: 10px;" class="container is-fluid message is-success">
              <div class="message-header">
                <p><strong>Sucesso !</strong></p>
                <button class="delete"></button>
              </div>
              <div class="message-body">
              <%= flash[key] %>
              </div>
            </article>
          <% end %>
        <% end %>
      <% end %>
    	<%= yield %>
  	</div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brisadao Blog | <%=yield(:page_title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bulma' %>
    <link href="https://use.fontawesome.com/d5100610f6.css" media="all" rel="stylesheet">
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="<%= controller_name %> <%= action_name %>">
    	<%= yield %>
  	</div>
  </body>
</html>